export const USER_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_OWNER: 'TENANT_OWNER',
  TENANT_MANAGER: 'TENANT_MANAGER',
  STAFF: 'STAFF',
} as const;

export const FEATURE_MODULES = {
  RESTAURANT: 'RESTAURANT',
  HOSPITALITY: 'HOSPITALITY',
} as const;
